### ISSUE TITLE
Traceback when there's no file permissions

### ISSUE THREAD

**Issue by iranzo** [fatherlinux/petit#16]
~~~console
Traceback (most recent call last):
  File "/home/iranzo/.local/bin/petit", line 446, in <module>
    get_options()
  File "/home/iranzo/.local/bin/petit", line 233, in get_options
    eval(options.mode + "()")
  File "<string>", line 1, in <module>
  File "/home/iranzo/.local/bin/petit", line 246, in mode_hash
    log = CrunchLog(filename)
  File "/home/iranzo/.local/venvs/petitlog/lib/python3.7/site-packages/crunchtools/CrunchLog.py", line 68, in __init__
    self.f = open(filename)
PermissionError: [Errno 13] Permission denied: '/var/log/messages'
Exception ignored in: <function CrunchLog.__del__ at 0x7f4b68b4c290>
Traceback (most recent call last):
  File "/home/iranzo/.local/venvs/petitlog/lib/python3.7/site-packages/crunchtools/CrunchLog.py", line 98, in __del__
    self.f.close()
AttributeError: 'CrunchLog' object has no attribute 'f'

~~~

**Comment by fatherlinux** [comment]
Fixed in #18 (merged), four years late — sorry about that, @iranzo.

Your report was still reproducible last week:

```
$ petit --hash /tmp/noperm.log
PermissionError: [Errno 13] Permission denied: '/tmp/noperm.log'
```

Now:

```
$ petit --hash /tmp/noperm.log
petit: cannot read /tmp/noperm.log: Permission denied     (exit 1)
```

I went a different route than your PR #17: catching `OSError` from `open()` rather than checking `os.access()` first. Two reasons — `os.access()` is a TOCTOU race (the file can change between the check and the open), and it answers "are the permission bits right?" rather than "can I actually open this", which differ under ACLs, SELinux, and read-only mounts. Same path now also covers a missing file.

Your diagnosis was correct and the bug was real. You're credited in the CHANGELOG and in the regression tests (`test/test_api.py::TestFileErrors`).

While I was in there, the same release removed the 13 `sys.exit()` calls from library code so failures raise `PetitError` instead — your PR exited `-1` from inside the library, which was the pattern that made this class of bug awkward to fix properly.
